In [2]:
pwd

'/tf/MolCLR-master - 복사본 - 복사본'

In [1]:
datasets = ['FreeSolv', 'ESOL', 'Lipo', 'qm7', "bace",  "bbbp",  'tox21', 'clintox', 'sider',]
seeds = [777, 778, 779, 780, 781]

for dataset in datasets:
    for seed in seeds:
            if dataset == 'FreeSolv':
            # FreeSolv 데이터셋에 대한 특정 옵션을 적용
                !python finetune3_gcn.py \
                --task_name {dataset} \
                --seed {seed} \
                --dropout 0.5 \
                --num_layer 3 \
                --emb_dim 64 \
                --feat_dim 64 \
                --gpu cuda:1 \
                --model_type gcn
                
            elif dataset == 'clintox':
                !python finetune3_gcn.py \
                --task_name {dataset} \
                --seed {seed} \
                --emb_dim 64 \
                --feat_dim 64 \
                --gpu cuda:1 \
                --model_type gcn
                
            else:
                !python finetune3_gcn.py \
                --task_name {dataset} \
                --seed {seed} \
                --gpu cuda:1 \
                --model_type gcn
                

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:1', 'task_name': 'freesolv', 'model_type': 'gcn', 'model': {'num_layer': 3, 'emb_dim': 64, 'feat_dim': 64, 'drop_ratio': 0.5, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 777, 'task': 'regression', 'data_path': 'data/freesolv/freesolv.csv', 'target': ['expt']}}
Running on: cuda:1
641
About to generate scaffolds
Generating scaffold 0/641
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
0 0 15.78664779663086
Validation loss: 72.35061836242676 RMSE: 8.505917
Validation loss: 70.42454719543457 R

In [1]:
seeds = list(range(777,782))
# datasets = ["bace",  "bbbp", "tox21", "toxcast", "sider",  ]
datasets = [  'clintox',  ]


for dataset in datasets:
    for seed in seeds: 
                !python finetune3_gcn.py \
                --task_name {dataset} \
                --seed {seed} \
                --emb_dim 64 \
                --feat_dim 64 \
                --gpu cuda:1 \
                --model_type gcn

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:1', 'task_name': 'clintox', 'model_type': 'gcn', 'model': {'num_layer': 5, 'emb_dim': 64, 'feat_dim': 64, 'drop_ratio': 0.3, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 777, 'task': 'classification', 'data_path': 'data/clintox/clintox.csv', 'target': ['CT_TOX', 'FDA_APPROVED']}}
Running on: cuda:1
1476
About to generate scaffolds
Generating scaffold 0/1476
Generating scaffold 1000/1476
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
0 0 0.7126062512397766
Validation loss: 0.655791949581455

In [ ]:
seeds = list(range(777,782))
# datasets = ["bace",  "bbbp", "tox21", "toxcast", "sider",  ]
datasets = [ 'tox21', 'clintox', 'sider', ]
for dataset in datasets:
    for seed in seeds: 
        !python finetune3.py \
        --task_name {dataset} \
        --splitting scaffold \
        --seed {seed} \

In [ ]:
seeds = list(range(777,782))
# datasets = ["bace",  "bbbp", "tox21", "toxcast", "sider",  ]
datasets = ["freeSolv",  "lipo", "esol", "qm7", "bace",  "bbbp", ]

for dataset in datasets:
    for seed in seeds: 
        !python finetuneRecon.py \
        --task_name {dataset} \
        --splitting scaffold \
        --seed {seed} \
        --alpha 0.1

In [1]:
for seed in seeds:
    !python finetuneReconFrag.py \
    --task_name freeSolv \
    --splitting scaffold \
    --seed 752

NameError: name 'seeds' is not defined

In [ ]:
!python finetune3_gcn.py \
--task_name FreeSolv \
--seed 999 \
--gpu cuda:1 \
--model_type gcn

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:1', 'task_name': 'freesolv', 'model_type': 'gcn', 'model': {'num_layer': 5, 'emb_dim': 300, 'feat_dim': 300, 'drop_ratio': 0.3, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 999, 'task': 'regression', 'data_path': 'data/freesolv/freesolv.csv', 'target': ['expt']}}
Running on: cuda:1
641
About to generate scaffolds
Generating scaffold 0/641
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
0 0 21.76392936706543
Validation loss: 46.63077735900879 RMSE: 6.828673
Validation loss: 40.11814308166504

In [ ]:
!python finetune3_gcn.py \
--task_name freeSolv \
--seed 740 \
--dropout 0.5 \
--num_layer 3 \
--emb_dim 64 \
--feat_dim 64 \
--gpu cuda:0 \
--model_type gcn

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:1', 'task_name': 'freesolv', 'model_type': 'gin', 'model': {'num_layer': 3, 'emb_dim': 64, 'feat_dim': 64, 'drop_ratio': 0.5, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 740, 'task': 'regression', 'data_path': 'data/freesolv/freesolv.csv', 'target': ['expt']}}
Running on: cuda:1
641
About to generate scaffolds
Generating scaffold 0/641
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
0 0 22.66116714477539
Validation loss: 70.69124031066895 RMSE: 8.407808
Validation loss: 65.4097785949707 RM

In [4]:
import torch
import torch.nn as nn

# 0과 1로 구성된 범주형 변수의 임베딩 설정
num_categories = 2  # 범주의 개수 (0과 1)
emb_dim = 10  # 임베딩 차원

# nn.Embedding 레이어 생성
embedding_layer = nn.Embedding(num_embeddings=num_categories, embedding_dim=emb_dim)

# 범주형 변수의 인덱스를 나타내는 텐서 생성
# 예를 들어, [1, 0, 1, 1, 0]와 같은 텐서를 가정합니다.
category_indices = torch.tensor([1, 0, 1, 1, 0])

# 범주형 변수의 인덱스를 임베딩 레이어에 전달하여 임베딩 벡터를 조회
embedded = embedding_layer(category_indices)

print("Category indices:", category_indices)
print("Embedded vectors:\n", embedded)


Category indices: tensor([1, 0, 1, 1, 0])
Embedded vectors:
 tensor([[-1.1825, -0.9537,  1.0269,  1.1472,  0.4052, -1.2119,  1.9069, -1.1420,
         -1.9693,  1.1902],
        [-0.6348, -0.2631,  0.6851, -0.1353, -0.8161,  1.4514, -2.0473,  0.1509,
         -1.0221, -1.5114],
        [-1.1825, -0.9537,  1.0269,  1.1472,  0.4052, -1.2119,  1.9069, -1.1420,
         -1.9693,  1.1902],
        [-1.1825, -0.9537,  1.0269,  1.1472,  0.4052, -1.2119,  1.9069, -1.1420,
         -1.9693,  1.1902],
        [-0.6348, -0.2631,  0.6851, -0.1353, -0.8161,  1.4514, -2.0473,  0.1509,
         -1.0221, -1.5114]], grad_fn=<EmbeddingBackward0>)


In [7]:
import torch.nn as nn
import torch
# 가정: x는 입력 데이터 텐서, emb_dim은 원하는 임베딩 차원입니다.
emb_dim = 300  # 예시 임베딩 차원

x = torch.rand((100,8))
# Linear 레이어 초기화: 6차원 입력을 emb_dim 차원 출력으로 변환
x_embedding3 = nn.Linear(6, emb_dim)

# x[:,2:]를 Linear 레이어에 전달
x_transformed = x_embedding3(x[:,2:])

print("Transformed shape:", x_transformed.shape) 

Transformed shape: torch.Size([100, 300])


In [7]:
category_indices.shape

torch.Size([5])

In [8]:
embedded.shape

torch.Size([5, 10])

In [10]:
# 임베딩 설정: 총 10개의 범주형 태그와 각 태그에 대한 5차원 임베딩 벡터
num_chirality_tags = 10  # 범주형 태그의 개수 (예: 0~9까지의 태그)
emb_dim = 5  # 임베딩 차원

# nn.Embedding 인스턴스 생성
embedding = nn.Embedding(num_chirality_tags, emb_dim)

# 다차원 입력 텐서 생성
# 예를 들어, 2x3 크기의 텐서로, 각 요소는 특정 범주형 태그의 인덱스
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 임베딩 적용
embedded_tensor = embedding(input_tensor)

embedded_tensor.shape, embedded_tensor

(torch.Size([2, 3, 5]),
 tensor([[[-0.8384, -0.6729,  0.2846,  0.4423, -1.3507],
          [ 1.1084, -1.5312,  0.2718, -0.4837,  1.8607],
          [ 0.3326, -0.1193, -0.8705, -0.6009, -0.4164]],
 
         [[-1.0632,  1.0288,  0.5488, -1.7929,  0.3330],
          [ 1.5004, -0.4843, -0.9040,  0.6776, -1.0243],
          [ 3.4435, -0.6644,  0.6785, -1.0914,  1.7393]]],
        grad_fn=<EmbeddingBackward0>))

In [11]:
input_tensor.shape

torch.Size([2, 3])

In [52]:
import torch
from torch_geometric.data import Data

# 노드 특성의 차원 (임의로 설정)
node_feature_dim = 64
num_nodes = 8  # 노드의 수 (임의로 설정)
num_edges = 12  # 엣지의 수 (임의로 설정)
edge_feature_dim = 10

# 노드 특성 생성 (노드 수 x 노드 특성 차원)
node_features = torch.randn(num_nodes, node_feature_dim)

# 엣지 인덱스 생성 (2 x 엣지 수) - 각 엣지는 (시작 노드, 종료 노드) 쌍으로 표현
# 예를 들어, 0번 노드에서 1번 노드로의 엣지, 1번 노드에서 2번 노드로의 엣지 등
edge_index = torch.randint(0, num_nodes, (2, num_edges), dtype=torch.long)

# 엣지 특성 생성 (엣지 수 x 엣지 특성 차원)
edge_features = torch.randn(num_edges, edge_feature_dim)

# 데이터 객체 생성
data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_features)

data

Data(x=[8, 64], edge_index=[2, 12], edge_attr=[12, 10])

In [59]:
from typing import Callable, Optional, Union

import torch
from torch import Tensor

from torch_geometric.nn.conv import MessagePassing
from torch_geometric.nn.dense.linear import Linear
from torch_geometric.nn.inits import reset
from torch_geometric.typing import (
    Adj,
    OptPairTensor,
    OptTensor,
    Size,
    SparseTensor,
)
from torch_geometric.utils import spmm

In [117]:
class GINEConv(MessagePassing):

    def __init__(self, nn: torch.nn.Module, eps: float = 0.,
                 train_eps: bool = False, edge_dim: Optional[int] = None,
                 **kwargs):
        kwargs.setdefault('aggr', 'add')
        super().__init__(**kwargs)
        self.nn = nn
        self.initial_eps = eps
        if train_eps:
            self.eps = torch.nn.Parameter(torch.empty(1))
        else:
            self.register_buffer('eps', torch.empty(1))
        if edge_dim is not None:
            if isinstance(self.nn, torch.nn.Sequential):
                nn = self.nn[0]
            if hasattr(nn, 'in_features'):
                in_channels = nn.in_features
            elif hasattr(nn, 'in_channels'):
                in_channels = nn.in_channels
            else:
                raise ValueError("Could not infer input channels from `nn`.")

            self.lin = Linear(edge_dim, 64)

        else:
            self.lin = None
        self.reset_parameters()

    def reset_parameters(self):
        reset(self.nn)
        self.eps.data.fill_(self.initial_eps)
        if self.lin is not None:
            self.lin.reset_parameters()

    def forward(
        self,
        x: Union[Tensor, OptPairTensor],
        edge_index: Adj,
        edge_attr: OptTensor = None,
        size: Size = None,
    ) -> Tensor:

        if isinstance(x, Tensor):
            x = (x, x)

        # propagate_type: (x: OptPairTensor, edge_attr: OptTensor)
        out = self.propagate(edge_index, x=x, edge_attr=edge_attr, size=size)

        x_r = x[1]
        if x_r is not None:
            out = out + (1 + self.eps) * x_r

        return self.nn(out)

    def message(self, x_j: Tensor, edge_attr: Tensor) -> Tensor:
        if self.lin is None and x_j.size(-1) != edge_attr.size(-1):
            raise ValueError("Node and edge feature dimensionalities do not "
                             "match. Consider setting the 'edge_dim' "
                             "attribute of 'GINEConv'")

        if self.lin is not None:
            edge_attr = self.lin(edge_attr)

        print(x_j.shape, edge_attr.shape)

        return (x_j + edge_attr).relu()

    def __repr__(self) -> str:
        return f'{self.__class__.__name__}(nn={self.nn})'

In [118]:
import torch
from torch.nn import Sequential, Linear, ReLU

# GINEConv 레이어의 내부 MLP 정의
# 엣지 특성의 차원
edge_feature_dim = 10
node_feature_dim = 64  # 노드 특성 차원과 일치해야 함
emb_dim  = 128

# 수정된 GINEConv 레이어의 내부 MLP 정의
nn = Sequential(Linear(node_feature_dim, 32), ReLU(), Linear(32, 64))  # 출력 차원을 64로 설정

# GINEConv 레이어 초기화
conv = GINEConv(nn, edge_dim=edge_feature_dim)

# GINEConv 레이어 초기화

# 노드 특성, 엣지 인덱스, 엣지 특성 정의 (위에서 생성한 Data 객체 사용)
num_nodes = 5
node_feature_dim = 64
num_edges = 4

x = torch.randn((num_nodes, node_feature_dim))  # 노드 특성


edge_index = torch.randint(0, num_nodes, (2, num_edges))  # 엣지 인덱스
edge_attr = torch.randn((num_edges, edge_feature_dim))  # 엣지 특성

In [119]:
print(x.shape, edge_index.shape, edge_attr.shape)

torch.Size([5, 64]) torch.Size([2, 4]) torch.Size([4, 10])


In [120]:
# GINEConv 레이어를 사용해 그래프 데이터 처리
# x는 노드 특성, edge_index는 그래프의 연결성을 나타내며, edge_attr은 각 엣지의 특성입니다.
out = conv(x=x, edge_index = edge_index, edge_attr = edge_attr)

print(out)

torch.Size([4, 64]) torch.Size([4, 64])
tensor([[ 2.0420e-01, -3.1109e-01,  4.9108e-01, -2.6704e-01, -4.6007e-01,
          4.6386e-01,  1.0325e-01,  1.1291e-01, -4.9992e-01, -3.0251e-01,
         -1.1335e-01, -1.0341e-01, -1.6714e-01,  3.1707e-01, -1.7417e-01,
          3.2802e-01,  1.0698e-01, -1.5301e-01,  5.6688e-01,  5.4748e-01,
         -3.1108e-01, -5.1276e-01, -8.4459e-02, -1.1048e-02, -2.6747e-01,
         -1.1287e-01,  4.4023e-01,  1.1810e-01,  1.8918e-01, -4.4333e-01,
         -2.8919e-01, -2.8419e-01, -2.4550e-01,  1.6701e-01, -1.5116e-01,
         -5.0157e-01,  6.1078e-01,  1.6841e-01,  1.2622e-01, -2.7580e-01,
          1.8768e-01, -9.6723e-02,  3.5140e-01, -1.2310e-02, -3.7161e-01,
          5.9052e-01,  3.8407e-01, -9.4807e-02, -2.4088e-01, -6.7466e-02,
         -1.0834e-01, -3.8428e-01,  5.8811e-01, -8.4075e-01,  4.1190e-01,
          2.7939e-01,  2.2606e-01,  2.3593e-01,  3.0628e-01,  3.7400e-01,
          1.1704e-02, -4.4872e-01,  1.2067e-02, -1.6160e-01],
        [ 