In [2]:
datasets = [ 'ESOL', 'Lipo', 'qm7', "bace",  "bbbp",  'tox21', 'clintox', 'sider']
seeds = [777, 778, 779, 780, 781]

for dataset in datasets:
    for seed in seeds:
            if dataset == 'FreeSolv':
            # FreeSolv 데이터셋에 대한 특정 옵션을 적용
                !python finetuneReconAlpha2.py \
                --task_name {dataset} \
                --seed {seed} \
                --dropout 0.5 \
                --num_layer 3 \
                --emb_dim 64 \
                --feat_dim 64 \
                --alpha 0.1 \
                --mask_edge 1 \
                --gpu cuda:1 
            
            elif dataset == 'clintox':
                !python finetuneReconAlpha2.py \
                --task_name {dataset} \
                --seed {seed} \
                --dropout 0.3 \
                --num_layer 5 \
                --emb_dim 64 \
                --feat_dim 64 \
                --alpha 0.1 \
                --mask_edge 1 \
                --gpu cuda:1

            else:
                !python finetuneReconAlpha2.py \
                --task_name {dataset} \
                --seed {seed} \
                --alpha 0.1 \
                --mask_edge 1 \
                --gpu cuda:1

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:1', 'task_name': 'esol', 'model_type': 'gin', 'model': {'num_layer': 5, 'emb_dim': 300, 'feat_dim': 300, 'drop_ratio': 0.3, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 777, 'task': 'regression', 'data_path': 'data/esol/esol.csv', 'target': ['measured log solubility in mols per litre']}}
Running on: cuda:1
1127
About to generate scaffolds
Generating scaffold 0/1127
Generating scaffold 1000/1127
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
0 0 14.863460540771484
Validation loss: 3.4459083

In [2]:
seeds = list(range(777,782))
# datasets = ["bace",  "bbbp", "tox21", "toxcast", "sider",  ]
datasets = ["freeSolv" ]

for dataset in datasets:
    for seed in seeds: 
        !python finetuneReconAlpha2.py \
        --task_name {dataset} \
        --splitting scaffold \
        --seed {seed} \
        --alpha 0.1

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:0', 'task_name': 'freesolv', 'model_type': 'gin', 'model': {'num_layer': 5, 'emb_dim': 300, 'feat_dim': 300, 'drop_ratio': 0.3, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 777, 'task': 'regression', 'data_path': 'data/freesolv/freesolv.csv', 'target': ['expt']}}
Running on: cuda:0
641
About to generate scaffolds
Generating scaffold 0/641
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
Traceback (most recent call last):
  File "/tf/MolCLR-master - copy2/finetuneReconAlpha.py", line 733, in 

In [1]:
for seed in seeds:
    !python finetuneReconAlpha2.py \
    --task_name bbbp \
    --splitting scaffold \
    --seed {seed}

NameError: name 'seeds' is not defined

In [1]:
!python finetuneReconAlpha.py \
    --task_name bbbp \
    --splitting scaffold \
    --seed 750 \
    --mask_edge 1 \
    --alpha 0.1

Please install apex for mixed precision training from: https://github.com/NVIDIA/apex
{'batch_size': 32, 'epochs': 200, 'eval_every_n_epochs': 1, 'fine_tune_from': 'pretrained_gin', 'log_every_n_steps': 50, 'fp16_precision': False, 'init_lr': 0.0005, 'init_base_lr': 0.0001, 'weight_decay': '1e-6', 'gpu': 'cuda:0', 'task_name': 'bbbp', 'model_type': 'gin', 'model': {'num_layer': 5, 'emb_dim': 300, 'feat_dim': 300, 'drop_ratio': 0.3, 'pool': 'mean'}, 'dataset': {'num_workers': 4, 'valid_size': 0.1, 'test_size': 0.1, 'splitting': 'scaffold', 'seed': 750, 'task': 'classification', 'data_path': 'data/bbbp/BBBP.csv', 'target': ['p_np']}}
Running on: cuda:0
2038
About to generate scaffolds
Generating scaffold 0/2038
Generating scaffold 1000/2038
Generating scaffold 2000/2038
About to sort in scaffold sets
pred_head.0.weight True
pred_head.0.bias True
pred_head.2.weight True
pred_head.2.bias True
pred_head.4.weight True
pred_head.4.bias True
0 0 1.1634025573730469
0 50 0.45289626717567444
Vali

In [1]:
!python finetuneReconAlpha2.py \
--task_name bbbp \
--splitting scaffold \
--mask_rate 0.7
--seed 445 \
--random_masking 1 \
--alpha 0.1 \
--mask_edge 1 

SyntaxError: invalid syntax (2438108354.py, line 2)

In [1]:
import torch

In [2]:
num_nodes = 10
num_classes = 3

In [5]:
pred_node = torch.randn(num_nodes, num_classes)

In [6]:
mask_node_label = torch.randint(0,num_classes, (num_nodes, 1))

In [9]:
_, prediced_classes = torch.max(pred_node, dim = 1)

In [12]:
a, prediced_classes = torch.max(pred_node, dim = 1)

In [11]:
pred_node

tensor([[-0.4224,  2.0152, -0.8221],
        [-0.6797,  0.7852,  0.8896],
        [ 1.0098, -0.3531,  0.5847],
        [ 0.5771,  0.8337, -0.1788],
        [-0.8700,  0.0082,  0.2619],
        [-1.1317, -1.1674, -0.2489],
        [ 1.7766, -0.0508, -0.0692],
        [-0.8634, -1.4741,  1.3934],
        [-0.4561,  0.9929, -0.2693],
        [ 0.5695, -0.1895, -0.2701]])

In [10]:
prediced_classes

tensor([1, 2, 0, 1, 2, 2, 0, 2, 1, 0])

In [15]:
mask_node_label

tensor([[2],
        [1],
        [2],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2]])

In [16]:
correct_predictions = (prediced_classes == mask_node_label[:,0])

In [17]:
correct_predictions

tensor([False, False, False,  True, False,  True, False,  True, False, False])

In [18]:
accuracy = correct_predictions.float().mean()

In [19]:
accuracy

tensor(0.3000)

In [20]:
accuracy.item()

0.30000001192092896